version: '3.6'

services:
  web:
    build: .
    command: >
      bash -c "python3 proforient/manage.py makemigrations admin 
      && python3 proforient/manage.py makemigrations user 
      && python3 proforient/manage.py makemigrations specialist 
      && python3 proforient/manage.py makemigrations service 
      && python3 proforient/manage.py makemigrations modelUtils 
      && python3 proforient/manage.py migrate 
      && python3 proforient/manage.py runserver 0.0.0.0:8000"
      

    volumes:
      - .:/proforient
    ports:
      - "8000:8000"
