# Generated by Django 2.1.2 on 2018-10-25 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('second_name', models.CharField(default=None, max_length=100)),
                ('third_name', models.CharField(default=None, max_length=100)),
                ('education', models.TextField(default=None, null=True)),
                ('workExpirience', models.TextField(default=None, null=True)),
                ('about_me', models.TextField(default=None, null=True)),
                ('is_specialist', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
